# Exercise 2.B Cleaning up data

In [1]:
# Import numpy and pandas 
import numpy as np
import pandas as pd

In [2]:
# In a code cell, create a new DataFrame named df based on test_data.csv (as saved
# from the previous exercise)
df = pd.read_csv('test_data.csv')
df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [3]:
# Add a cell to show column statistics on df using the describe method
df.describe()

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

In [4]:
# Filter the DataFrame to show only rows where Age is greater than 18.
df_age_over_18 = df[df['Age'] > 18]

df_age_over_18

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

In [5]:
# Filter the DataFrame to show only rows where Score is greater than 50 and less than 100
df_score_range = df[(df['Score'] > 50) & (df['Score'] < 100)]

df_score_range

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [6]:
# Create new variable df_cleaned. Assign it the value of df, using the drop function to remove rows where the Score is less than 0 
#(i.e., invalid score data). Then call df_cleaned to review the result

# We create a new DataFrame called df_cleaned
# drop() is used to remove rows that meet a condition
# Here: remove rows where Score < 0 (invalid data)

df_cleaned = df.drop(df[df["Score"] < 0].index)

# Display the cleaned DataFrame
df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [7]:
# Continuing to work with df_cleaned for the rest of these steps, remove the City
# column from the DataFrame using drop. Call df_cleaned to review the result

# We continue working with df_cleaned
# axis=1 means we are removing a column (not rows)

df_cleaned = df_cleaned.drop("City", axis=1)

# Display the DataFrame after removing City
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

In [8]:
# Replace all missing Age values with the mean Age of the DataFrame using fillna.
# Call df_cleaned to review the result

# Calculate the mean (average) age, ignoring NaN automatically
mean_age = df_cleaned["Age"].mean()

# fillna() replaces NaN values with the mean age
df_cleaned["Age"] = df_cleaned["Age"].fillna(mean_age)

# Display the updated DataFrame
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [9]:
# Replace any Score value of 0 with the mean Score of the DataFrame using replace.
# Call df_cleaned to review the result.
mean_score = df_cleaned["Score"].mean() # Calculate the mean Score

df_cleaned["Score"] = df_cleaned["Score"].replace(0, mean_score)  # replace() changes Score values of 0 into the mean Score

df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [10]:
# Remove any remaining rows that contain NaN values using the dropna function.
# Call df_cleaned to review the result.

df_cleaned = df_cleaned.dropna() # dropna() removes any row that still has NaN values

# Display the cleaned DataFrame
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [11]:
# Apply the values from ID as index labels, then remove column ID. (Pay attention to
# the numbering!) Call df_cleaned to review the result

# set_index() moves the ID column to be the index (row labels)
df_cleaned = df_cleaned.set_index("ID")

# Display the final cleaned DataFrame
df_cleaned

       Name   Age  Score
ID
1    Alicia  25.0   85.0
2       Bob  25.6   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
7     Grace  25.6   55.0
8     Heidi  18.0   90.0