# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
# Create a DataFrame named df_sales using the following data:
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

# Convert dictionary into DataFrame
df_sales = pd.DataFrame(data)

# Display DataFrame
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [3]:
# Add a new column Revenue to df_sales by multiplying Units_Sold and Price.

# Revenue = Units_Sold × Price
df_sales["Revenue"] = df_sales["Units_Sold"] * df_sales["Price"]

# Show updated DataFrame
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [4]:
# Use the sum function to calculate the total Units_Sold and total Revenue across all products and regions.

# Sum of all Units_Sold
total_units = df_sales["Units_Sold"].sum()

# Sum of all Revenue
total_revenue = df_sales["Revenue"].sum()

# Print results
print("Total Units Sold:", total_units)
print("Total Revenue:", total_revenue)

Total Units Sold: 105
Total Revenue: 16000

In [5]:
# Use the mean function to calculate the average Units_Sold and average Revenue

# Average Units Sold
avg_units = df_sales["Units_Sold"].mean().round(2)

# Average Revenue
avg_revenue = df_sales["Revenue"].mean().round(2)

# Print results
print("Average Units Sold:", avg_units)
print("Average Revenue:", avg_revenue)

Average Units Sold: 11.67
Average Revenue: 1777.78

## Grouping Data

In [6]:
# Use the groupby function to group df_sales by Product and calculate the total Units_Sold and total Revenue for each product.
# Group by Product and calculate total Units_Sold and Revenue
# This means: combine all rows that have the same Product

df_sales.groupby("Product")[["Units_Sold", "Revenue"]].sum()

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [7]:
# Use the groupby function to group df_sales by Region and calculate the average Units_Sold and average Revenue for each region

# Group by Region and calculate average values
# This shows typical performance per region

df_sales.groupby("Region")[["Units_Sold", "Revenue"]].mean()

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [8]:
# Use the groupby function to group df_sales by both Product and Region and calculate the sum of Units_Sold and Revenue for each combination.
# Group by BOTH Product and Region
# This creates subgroups (like a matrix)

df_sales.groupby(["Product", "Region"])[["Units_Sold", "Revenue"]].sum()

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [9]:
# Sort from smallest to largest Units_Sold
# ascending=True is default, but we write it for clarity
df_sales.sort_values(by="Units_Sold", ascending=True)

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
0       A  North          10    100     1000
4       B  North          10    200     2000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [10]:
#Sort df_sales by Revenue in descending order.
# Sort from highest to lowest Revenue
df_sales.sort_values(by="Revenue", ascending=False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [11]:
 # Add a new column Revenue_Rank to df_sales, which ranks the Revenue values in descending order (i.e., highest revenue has rank 1
# Rank Revenue in descending order
# highest revenue = rank 1
df_sales['Rank'] = df_sales['Revenue'].rank(ascending=False,method='dense').astype(int)
# Show updated DataFrame
df_sales

  Product Region  Units_Sold  Price  Revenue  Rank
0       A  North          10    100     1000     4
1       B  South          15    200     3000     1
2       C   East          20    150     3000     1
3       A   West           5    100      500     5
4       B  North          10    200     2000     3
5       C  South          15    150     2250     2
6       A   East          10    100     1000     4
7       B   West           5    200     1000     4
8       C  North          15    150     2250     2

In [13]:
# Show final DataFrame with all changes
df_sales

  Product Region  Units_Sold  Price  Revenue  Rank
0       A  North          10    100     1000     4
1       B  South          15    200     3000     1
2       C   East          20    150     3000     1
3       A   West           5    100      500     5
4       B  North          10    200     2000     3
5       C  South          15    150     2250     2
6       A   East          10    100     1000     4
7       B   West           5    200     1000     4
8       C  North          15    150     2250     2

## Merging DataFrames

In [16]:
# Create a new DataFrame named df_products with the following data:
product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}

df_products = pd.DataFrame(product_data)

# Show the DataFrame
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [17]:
# Merge df_sales with df_products on the Product column, resulting in a new DataFrame named df_merged
# Merge df_sales and df_products using the "Product" column
# This combines information from both tables

df_merged = pd.merge(df_sales, df_products, on="Product")

# Show result
df_merged

  Product Region  Units_Sold  Price  Revenue  Rank     Category
0       A  North          10    100     1000     4  Electronics
1       B  South          15    200     3000     1    Furniture
2       C   East          20    150     3000     1   Appliances
3       A   West           5    100      500     5  Electronics
4       B  North          10    200     2000     3    Furniture
5       C  South          15    150     2250     2   Appliances
6       A   East          10    100     1000     4  Electronics
7       B   West           5    200     1000     4    Furniture
8       C  North          15    150     2250     2   Appliances

In [18]:
# Just display the merged result

df_merged

  Product Region  Units_Sold  Price  Revenue  Rank     Category
0       A  North          10    100     1000     4  Electronics
1       B  South          15    200     3000     1    Furniture
2       C   East          20    150     3000     1   Appliances
3       A   West           5    100      500     5  Electronics
4       B  North          10    200     2000     3    Furniture
5       C  South          15    150     2250     2   Appliances
6       A   East          10    100     1000     4  Electronics
7       B   West           5    200     1000     4    Furniture
8       C  North          15    150     2250     2   Appliances

In [20]:
# Calculate total Revenue per Category

df_merged.groupby("Category")["Revenue"].sum()

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64